- name: install and run nginx service
  hosts: web
  become: true
  tasks:
  - name: install nginx
    ansible.builtin.package:
     state: present

  - name: run nginx service
    ansible.builtin.service:
     state: started
     enabled: true